### ISSUE TITLE
Heroku Doesn't work

### ISSUE THREAD

**Issue by sasial-roblox** [kenng69/modmailbotkenng#2]
![image](https://user-images.githubusercontent.com/44125644/46910579-5008f180-cf8a-11e8-84d3-441d301d8491.png)
This error above is the issue after I tap the link to it.

**Comment by kenng69** [comment]
The app.json file is located in the root directory of the repository. Please click the button again. If it doesn't work, email me at support@kenng.tk

**Comment by marioc22** [comment]
The same issue is happening to me!
